### ISSUE TITLE
Jabfox does not finish

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/JabFox#25] opened 2016-05-25 06:35 UTC
I noticed that the Jabfox plugin (on Win7, Firefox 46.0.1 and previous versions) imports citations into Jabref, but at the same time blocks firefox completely. This is a serious since informations in other firefox tabs get easily lost when one has to shutdown firefox. Please solve this issue asap.

**Comment by tobiasdiez** [comment] 2016-05-26 15:58
Duplicate of https://github.com/JabRef/jabref/issues/1275

**Closed by tobiasdiez** 2016-05-26 15:58 UTC
Labels: status:duplicate
