### ISSUE TITLE
Where should the JabFox entries end up in JabRef?

### ISSUE THREAD

**Issue by carbonmetrics** [JabRef/JabFox#37] opened 2017-06-05 15:14 UTC
After clicking on the JabRef button: "Import the following items into JabRef: "searching for bibliographic data...".

I see the item briefly appear in Zotero but nothing happens in JabRef. I have set the path to the JabRef jar. No idea how this works - where exactly is the reference added in JabRef?

**Comment by tobiasdiez** [comment] 2017-06-11 08:29
Sorry for the late replay. Normally JabRef should show the import dialog after you click the JabFox icon. Which operating system do you use? Did you tried to create the `.sh` script as outlined in the readme? Maybe this issue is related to https://github.com/JabRef/JabFox/issues/28.

**Comment by carbonmetrics** [comment] 2017-07-12 10:52
A late reply from me. I am Xubuntu 64, I tried the sh script and it did not make any difference.

**Comment by tobiasdiez** [comment] 2017-07-12 11:07
Mhhh...then I think your problem is really a duplicate of https://github.com/JabRef/JabFox/issues/28. I'm sorry for the inconvenience but right now there is nothing I can do to fix this issue.

**Closed by tobiasdiez** 2017-07-12 11:07 UTC
Labels: status:waiting-for-feedback
